spring:
  datasource:
    url: jdbc:postgresql://82.202.138.26:5430/hostelService

firebase:
  adminsdk:
    path: /app/service-for-dormitory-firebase-adminsdk-fbsvc-7745a3b8b1.json

otlp:
  tracing:
    endpoint: http://tempo.monitoring.svc.cluster.local:4317    