apiVersion: v1
kind: Service
metadata:
  name: notificationsservice
spec:
  selector:
    app: notificationsservice
  ports:
    - protocol: TCP
      port: 8080         # Внутренний порт, по которому шлюз доступен в кластере
      targetPort: 8080   # Порт, на котором слушает контейнер
  type: ClusterIP      # Так сервис доступен только внутри кластера; внешний доступ обеспечит Ingress или NodePort
